name: Build Installer

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name ps2exe -Force -Scope CurrentUser

      - name: Read version
        id: get_version
        run: |
          $version = Get-Content -Path 'repo/version/version.txt'  # Adjust the path to your version file
          Write-Output "::set-output name=version::$version"

      - name: Compile PowerShell script to executable
        shell: pwsh
        run: |
          $source = 'repo/latest/Realmsgate-Mini-Windows-Installer.ps1'
          $target = "Realmsgate-Mini-${{ steps.get_version.outputs.version }}-Windows-Installer.exe"
          Invoke-ps2exe -InputFile $source -OutputFile $target -NoConsole

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Realmsgate-Mini-Installer
          path: "Realmsgate-Mini-${{ steps.get_version.outputs.version }}-Windows-Installer.exe"
